language: go
sudo: false
go:
    - 1.4.3
    - 1.5.3
    - 1.6rc2
    - tip
before_script:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
    - go test -v -covermode=count -coverprofile=coverage.out
after_success:
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
